### ISSUE TITLE
Crash with quark forge 1.19.2

### ISSUE THREAD

**Issue by mxnmnm** [EterDelta/CrittersAndCompanions#49] opened 2023-12-09 07:45 UTC
Step 1: Make sure quark's guaranteed zombie villagers on normal difficulty is enabled with this mod installed
Step 2: Have zombies attack a villager
Step 3: Crash

Here is the report: https://gist.github.com/mxnmnm/e009b62ab98975e499fc4deb9b6cd7ae

**Comment by norfaremc** [comment] 2023-12-11 07:34
We are experiencing this issue as well, and right now our server is unplayable due to this.

**Comment by mxnmnm** [comment] 2023-12-11 07:55
you can turn off that feature in quark and it works

**Comment by EterDelta** [comment] 2023-12-19 01:04
Dupe of https://github.com/bonsaistudi0s/CrittersAndCompanions/issues/50
Closing in favor of the other issue, which is already being resolved, and contains more logs.

**Closed as completed by EterDelta** 2023-12-19 01:04 UTC
